from . import dtypes as dt
from .jit import JittedKernel, jit
from .tracer import (
    CooperativeTensor,
    MatmulOp,
    TensorHandle,
    TileSlice,
    abs,
    acos,
    asin,
    atan,
    atan2,
    atomic_exchange,
    atomic_fetch_add,
    atomic_fetch_and,
    atomic_fetch_max,
    atomic_fetch_min,
    atomic_fetch_or,
    atomic_fetch_sub,
    atomic_fetch_xor,
    atomic_load,
    atomic_store,
    cast,
    ceil,
    clamp,
    cos,
    cosh,
    exp,
    exp2,
    fabs,
    fast_cos,
    fast_exp,
    fast_log,
    fast_log2,
    fast_pow,
    fast_rsqrt,
    fast_sin,
    fast_sqrt,
    fast_tan,
    floor,
    fma,
    fmax,
    fmin,
    fmod,
    if_,
    local,
    log,
    log10,
    log2,
    matmul2d,
    max,
    min,
    pow,
    profile,
    range,
    round,
    rsqrt,
    sign,
    simd_all,
    simd_and,
    simd_any,
    simd_broadcast,
    simd_max,
    simd_min,
    simd_or,
    simd_prefix_exclusive_product,
    simd_prefix_exclusive_sum,
    simd_prefix_inclusive_product,
    simd_prefix_inclusive_sum,
    simd_product,
    simd_shuffle,
    simd_shuffle_down,
    simd_shuffle_up,
    simd_shuffle_xor,
    simd_sum,
    simd_xor,
    simdgroup_barrier,
    sin,
    sinh,
    sqrt,
    tan,
    tanh,
    tensor,
    threadgroup,
    threadgroup_barrier,
    trunc,
)
from .types import (
    DevicePointer,
    Int,
    Int2,
    Int3,
    ScalarParamSpec,
    SimdgroupIndexInThreadgroup,
    ThreadAttribute,
    ThreadIndexInSimdgroup,
    ThreadPositionInGrid,
    ThreadPositionInThreadgroup,
    ThreadgroupPositionInGrid,
    ThreadsPerGrid,
    ThreadsPerSimdgroup,
    ThreadsPerThreadgroup,
    Uint,
    Uint2,
    Uint3,
)

__all__ = [
    "dt",
    "jit",
    "JittedKernel",
    # Kernel-level control flow + memory
    "local",
    "range",
    "if_",
    "threadgroup",
    "threadgroup_barrier",
    "simdgroup_barrier",
    "cast",
    # Math intrinsics
    "exp", "exp2", "log", "log2", "log10", "sqrt", "rsqrt",
    "sin", "cos", "tan", "asin", "acos", "atan", "atan2",
    "sinh", "cosh", "tanh",
    "floor", "ceil", "round", "trunc",
    "fabs", "abs", "sign",
    "pow", "fmod", "fmin", "fmax", "min", "max",
    "clamp", "fma",
    "fast_exp", "fast_log", "fast_log2", "fast_sqrt", "fast_rsqrt",
    "fast_sin", "fast_cos", "fast_tan", "fast_pow",
    # Simd intrinsics
    "simd_sum", "simd_product", "simd_max", "simd_min",
    "simd_and", "simd_or", "simd_xor", "simd_all", "simd_any",
    "simd_prefix_inclusive_sum", "simd_prefix_exclusive_sum",
    "simd_prefix_inclusive_product", "simd_prefix_exclusive_product",
    "simd_broadcast", "simd_shuffle", "simd_shuffle_up",
    "simd_shuffle_down", "simd_shuffle_xor",
    # Atomics
    "atomic_load", "atomic_store",
    "atomic_fetch_add", "atomic_fetch_sub",
    "atomic_fetch_and", "atomic_fetch_or", "atomic_fetch_xor",
    "atomic_fetch_min", "atomic_fetch_max",
    "atomic_exchange",
    # MetalPerformancePrimitives
    "tensor", "matmul2d",
    "TensorHandle", "TileSlice", "MatmulOp", "CooperativeTensor",
    # Profiler
    "profile",
    # Parameter type specs
    "DevicePointer",
    "ScalarParamSpec",
    "Uint", "Uint2", "Uint3",
    "Int", "Int2", "Int3",
    # Attribute markers
    "ThreadAttribute",
    "ThreadPositionInGrid",
    "ThreadPositionInThreadgroup",
    "ThreadgroupPositionInGrid",
    "ThreadsPerThreadgroup",
    "ThreadsPerGrid",
    "ThreadsPerSimdgroup",
    "ThreadIndexInSimdgroup",
    "SimdgroupIndexInThreadgroup",
]
